name: ðŸ§‘â€ðŸ”§ Build Devcontainer

on:
  push:
    branches:
      - main
    paths:
      - ".devcontainer/**"
  pull_request:
    paths:
      - ".devcontainer/**"
  workflow_dispatch:
    inputs:
      run_tests:
        description: Run tests inside container
        type: boolean
        default: false

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-devcontainer:
    name: ðŸ³ Build Devcontainer
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout Repository
        uses: actions/checkout@v4

      - name: ðŸ”§ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ðŸ” Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸ³ Build Devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/jimmypaolini/monorepo-devcontainer
          cacheFrom: |
            type=gha,scope=devcontainer
            ghcr.io/jimmypaolini/monorepo-devcontainer
          cacheTo: type=gha,mode=max,scope=devcontainer
          push: filter
          eventFilterForPush: |
            push:
              branches:
                - main

  test-devcontainer:
    name: ðŸ”¬ Test Devcontainer
    runs-on: ubuntu-latest
    needs: build-devcontainer

    steps:
      - name: ðŸ“¥ Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ðŸ•‹ Setup Monorepo
        uses: ./.github/actions/setup-monorepo

      - name: ðŸ›‚ Change node_modules ownership
        run: sudo chown -R 1000:1000 node_modules

      - name: ðŸ”§ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ðŸ” Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸ©¹ Patch Configuration for Test
        run: jq 'del(.runArgs) | del(.mounts)' .devcontainer/devcontainer.json > /tmp/devcontainer.json && mv /tmp/devcontainer.json .devcontainer/devcontainer.json

      - name: ðŸ”¬ Test Devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/jimmypaolini/monorepo-devcontainer
          cacheFrom: |
            type=gha,scope=devcontainer
            ghcr.io/jimmypaolini/monorepo-devcontainer
          push: never
          runCmd: |
            bash .devcontainer/scripts/test-devcontainer.sh
